### ISSUE TITLE
Additive blending

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/tangram-reference#9]
Mapnik uses `"plus"` for additive blending, however, tangram-reference uses `"add"`.

`"add"` should be replaced by `"plus"` and the translation should be done in tangram-carto.

**Comment by IagoLast** [comment]
IMO we should check the subsets of comp-op functions that we are **currently** supporting.

(Tip: you can use the tangram.cartodb playground to test different maps).

Once we got the list, we should update this repo according to it and create issues for the not supported blend modes (comp-ops). (I think we should create a issue per symbolizer and mode, example: marker-multiply, polygon-add in order to have more granularity)

**Comment by davidmanzanares** [comment]
The list of currently supported ops is on https://github.com/CartoDB/tangram-reference/issues/7

We already have an issue for each operation, if we create one for each symbolizer we could be creating 15 issues.

**Comment by davidmanzanares** [comment]
Unfortunately, this is not as simple as fixing tangram-carto. Additive blending in Tangram is broken if outlines are used.  In fact, Tangram blending is broken in general if outlines are used. 
https://github.com/tangrams/tangram/pull/583 fixes the general case of using `src-over` but,  due to the way tangram renders the outlines, each blending mode will require support inside the shader (to blend between outline and fill) in top of the general support to blend between different features.

**Comment by davidmanzanares** [comment]
I'm gonna close this, see #7  since it is better described there.
